controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

portfolio_controllers:
    resource:
        path: ../src/Portfolio/Controller/
        namespace: App\Portfolio\Controller
    type: attribute

user_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute
