FROM node:20

RUN apt-get update && apt-get install -y iputils-ping curl

WORKDIR /workspace

COPY api ./api

WORKDIR /workspace/api
RUN npm install

COPY website/package*.json /workspace/website/

WORKDIR /workspace/website
RUN npm install

COPY website ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
