FROM node:20

RUN apt-get update && apt-get install -y iputils-ping curl

WORKDIR /workspace

ARG NEXT_PUBLIC_API_URL
ARG API_CLIENT_URL

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV API_CLIENT_URL=${API_CLIENT_URL}
ENV NEXT_TELEMETRY_DISABLED=1

COPY api ./api

WORKDIR /workspace/api
RUN npm install

COPY website/package*.json /workspace/website/

WORKDIR /workspace/website
RUN npm install

COPY website ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
