FROM oven/bun:1

RUN apt-get update && apt-get install -y iputils-ping curl

WORKDIR /workspace

ARG NEXT_PUBLIC_API_URL
ARG API_CLIENT_URL

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV API_CLIENT_URL=${API_CLIENT_URL}
ENV NEXT_TELEMETRY_DISABLED=1

# =====================
# API
# =====================

COPY api/package.json api/bun.lock* ./api/

WORKDIR /workspace/api
RUN bun install

COPY api ./

# =====================
# WEBSITE
# =====================

COPY website/package.json website/bun.lock* ../website/

WORKDIR /workspace/website
RUN bun install

COPY website ./

EXPOSE 3000

CMD ["bun", "run", "dev"]
